-- MySQL Script generated by MySQL Workbench
-- Wed 23 Dec 2015 04:36:16 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;

-- -----------------------------------------------------
-- Schema security
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema security
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `security` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `security` ;

-- -----------------------------------------------------
-- Table `security`.`form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`form` (
  `id_form` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name_form` VARCHAR(45) NOT NULL COMMENT '',
  `url_form` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id_form`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`rol` (
  `id_rol` INT NOT NULL COMMENT '',
  `name_rol` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rol`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`rol_form`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`rol_form` (
  `id_rol_form` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rol_id_rol` INT NOT NULL COMMENT '',
  `form_id_form` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rol_form`, `rol_id_rol`, `form_id_form`)  COMMENT '',
  INDEX `fk_rol_form_rol_idx` (`rol_id_rol` ASC)  COMMENT '',
  INDEX `fk_rol_form_form1_idx` (`form_id_form` ASC)  COMMENT '',
  CONSTRAINT `fk_rol_form_rol`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `security`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_form_form1`
    FOREIGN KEY (`form_id_form`)
    REFERENCES `security`.`form` (`id_form`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_user`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`user_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`user_rol` (
  `id_user_rol` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `rol_id_rol` INT NOT NULL COMMENT '',
  `user_id_user` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_user_rol`, `rol_id_rol`, `user_id_user`)  COMMENT '',
  INDEX `fk_user_rol_rol1_idx` (`rol_id_rol` ASC)  COMMENT '',
  INDEX `fk_user_rol_user1_idx` (`user_id_user` ASC)  COMMENT '',
  CONSTRAINT `fk_user_rol_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `security`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rol_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `security`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `security`.`sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security`.`sesion` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pid` DECIMAL(10,0) NOT NULL COMMENT '',
  `start_sesion` TIMESTAMP NOT NULL COMMENT '',
  `end_sesion` TIMESTAMP NOT NULL COMMENT '',
  `user_id_user` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_sesion`, `user_id_user`)  COMMENT '',
  INDEX `fk_sesion_user1_idx` (`user_id_user` ASC)  COMMENT '',
  CONSTRAINT `fk_sesion_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `security`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
